development:
  adapter: postgresql
  encoding: unicode
  database: final_development  #name is name of app _development 
  pool: 5
  host: localhost
  username: postgres
  password: gado595

production:
  adapter: postgresql
  encoding: unicode
  database: final_production  #name is name of app _development 
  pool: 5
  host: localhost
  username: postgres
  password: gado595